import re

def parse_sbi(text: str):
    transactions = []
    lines = text.splitlines()
    txn_id = 1
    
    for line in lines:
        # We look for lines with Pipes '|' (Generated by pdf_loader's table extraction)
        if "|" in line:
            parts = [p.strip() for p in line.split("|")]
            
            # SBI Table Structure:
            # 0: Txn Date
            # 1: Value Date (or Post Date)
            # 2: Description
            # 3: Ref No / Cheque
            # 4: Debit
            # 5: Credit
            # 6: Balance
            
            if len(parts) >= 7:
                date_str = parts[0]
                
                # Skip Header Rows
                if "Date" in date_str or "Txn" in date_str:
                    continue
                
                # Validate Date Format (DD/MM/YYYY or DD-MM-YYYY)
                if not re.match(r"\d{2}[/-]\d{2}[/-]\d{4}", date_str):
                    continue

                description = parts[2]

                # Helper to clean numbers
                def clean_amt(val):
                    # Remove commas, handle '-' or empty strings
                    val = val.replace(",", "").strip()
                    if not val or val == "-":
                        return 0.0
                    try:
                        return float(val)
                    except ValueError:
                        return 0.0

                debit = clean_amt(parts[4])
                credit = clean_amt(parts[5])
                balance = clean_amt(parts[6])
                
                # Valid transaction check
                if debit > 0 or credit > 0:
                    txn = {
                        "id": txn_id,
                        "txn_date": date_str,
                        "description": description,
                        "debit": debit if debit > 0 else None,
                        "credit": credit if credit > 0 else None,
                        "balance": balance,
                        "confidence": 1.0, # High confidence because it's from a Table
                        "is_flagged": False
                    }
                    transactions.append(txn)
                    txn_id += 1
                    
    return transactions